# Generated by Django 2.2.7 on 2019-11-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='', max_length=100)),
                ('host_email', models.CharField(default='', max_length=100)),
                ('host_phone', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
