# Generated by Django 2.2.7 on 2019-12-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorapp', '0002_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='checkin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='checkout',
            field=models.DateTimeField(),
        ),
    ]
